
USE pj_hermes;

INSERT INTO Materia_Prima (nome, descricao, preco) VALUES
('Couro Sintético A', 'Couro sintético para produção de calçados esportivos', 25.50),
('Solado de Borracha B', 'Solado de borracha antiderrapante para tênis', 12.90),
('Cola Industrial C', 'Cola industrial resistente à água para colagem de solados', 8.30),
('Tecido Respirável D', 'Tecido respirável para confecção de calçados', 18.00),
('Cadarço de Algodão E', 'Cadarços de algodão resistentes e duráveis', 2.50),
('Espuma para Palmilha F', 'Espuma de alta densidade para palmilhas', 10.20),
('Couro Natural G', 'Couro natural de alta qualidade para calçados', 55.00),
('Tecido Sintético H', 'Tecido sintético resistente para confecção de tênis', 22.30),
('Ferragem para Fechos I', 'Ferragem metálica para fechos de calçados', 5.60),
('Zíper Industrial J', 'Zíper industrial para calçados', 4.50),
('Couro Sintético K', 'Couro sintético para sapatos femininos', 23.75),
('Solado de EVA L', 'Solado de EVA leve e flexível', 14.50),
('Tecido de Algodão M', 'Tecido de algodão para forros internos de sapatos', 11.25),
('Espuma para Calcanhar N', 'Espuma para ajuste de calcanhar', 6.80),
('Tecido Impermeável O', 'Tecido impermeável para calçados de corrida', 19.95),
('Cadarço de Poliéster P', 'Cadarços de poliéster duráveis', 2.75),
('Couro Natural Q', 'Couro natural resistente para botas', 60.00),
('Cola Industrial R', 'Cola industrial resistente a altas temperaturas', 9.10),
('Ferragem para Fivelas S', 'Ferragem metálica para fivelas de calçados', 7.20),
('Tecido Sintético T', 'Tecido sintético para calçados de uso diário', 20.10),
('Solado de Borracha U', 'Solado de borracha resistente ao desgaste', 13.60),
('Couro Sintético V', 'Couro sintético para botas e coturnos', 26.40),
('Tecido Respirável W', 'Tecido respirável para tênis de corrida', 17.80),
('Cadarço de Nylon X', 'Cadarço de nylon reforçado', 2.95),
('Espuma para Palmilha Y', 'Espuma macia para palmilhas ortopédicas', 11.00),
('Couro Natural Z', 'Couro natural para calçados formais', 58.50),
('Solado de Borracha AA', 'Solado de borracha antiderrapante para botas', 16.20),
('Cola Industrial AB', 'Cola de secagem rápida para calçados', 7.50),
('Tecido de Malha AC', 'Tecido de malha leve para calçados esportivos', 15.60),
('Espuma de Alta Densidade AD', 'Espuma de alta densidade para solados', 13.90),
('Ferragem para Zíper AE', 'Ferragem metálica para zíperes de calçados', 4.80),
('Solado de EVA AF', 'Solado de EVA durável e leve', 13.00),
('Tecido de Algodão AG', 'Tecido de algodão resistente para sapatos casuais', 10.90),
('Cadarço de Couro AH', 'Cadarço de couro para botas', 3.50),
('Couro Sintético AI', 'Couro sintético para sapatos de inverno', 24.70),
('Tecido Respirável AJ', 'Tecido respirável para calçados casuais', 18.30),
('Cadarço de Poliéster AK', 'Cadarço de poliéster reforçado', 3.10),
('Solado de Borracha AL', 'Solado de borracha resistente para calçados infantis', 14.70),
('Couro Natural AM', 'Couro natural de alta durabilidade', 56.90),
('Espuma para Palmilha AN', 'Espuma de memória para palmilhas de conforto', 12.30),
('Cola Industrial AO', 'Cola resistente para calçados esportivos', 9.80),
('Tecido Sintético AP', 'Tecido sintético impermeável para calçados outdoor', 21.50),
('Ferragem para Fivelas AQ', 'Ferragem para fivelas de cintos e calçados', 6.90),
('Solado de EVA AR', 'Solado de EVA confortável para tênis', 15.20),
('Couro Sintético AS', 'Couro sintético de alta resistência', 27.90),
('Tecido de Malha AT', 'Tecido de malha respirável para calçados', 16.80),
('Cadarço de Algodão AU', 'Cadarço de algodão para tênis de corrida', 2.40),
('Espuma para Calcanhar AV', 'Espuma de alta densidade para ajuste de calcanhar', 7.00),
('Solado de Borracha AW', 'Solado de borracha flexível', 13.90),
('Couro Natural AX', 'Couro natural macio para calçados femininos', 57.80),
('Ferragem para Fechos AY', 'Ferragem para fechos de botas', 5.80),
('Cola Industrial AZ', 'Cola industrial para calçados casuais', 8.40);

select * from pj_hermes.materia_prima