-- MySQL Script generated by MySQL Workbench
-- Sat Oct 19 16:50:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pj_hermes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pj_hermes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pj_hermes` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pj_hermes` ;

-- -----------------------------------------------------
-- Table `pj_hermes`.`materia_prima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`materia_prima` (
  `idMateriaPrima` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idMateriaPrima`),
  INDEX `idx_materiaprima_nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`status_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`status_id` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `descricaoEstado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(100) NULL DEFAULT NULL,
  `CNPJ` VARCHAR(20) NULL DEFAULT NULL,
  `responsavel` VARCHAR(100) NULL DEFAULT NULL,
  `ramo` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `fk_idEstado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idFornecedor`),
  INDEX `idx_fornecedor_nome` (`nome` ASC) VISIBLE,
  INDEX `idx_fornecedor_cidade` (`cidade` ASC) VISIBLE,
  INDEX `fk_estado_fornec` (`fk_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_estado_fornec`
    FOREIGN KEY (`fk_idEstado`)
    REFERENCES `pj_hermes`.`status_id` (`idStatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`compra_materia_prima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`compra_materia_prima` (
  `idTransacaoCompra` INT NOT NULL AUTO_INCREMENT,
  `dataTransacao` DATE NULL DEFAULT NULL,
  `dataValidade` DATE NULL DEFAULT NULL,
  `totalCompra` DECIMAL(10,2) NOT NULL,
  `fk_idMateriaPrima` INT NULL DEFAULT NULL,
  `fk_idFornecedor` INT NULL DEFAULT NULL,
  `fk_idStatus` INT NULL DEFAULT NULL,
  `data_transacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idTransacaoCompra`),
  INDEX `idx_compra_dataTransacao` (`dataTransacao` ASC) VISIBLE,
  INDEX `idx_compra_materiaprima` (`fk_idMateriaPrima` ASC) VISIBLE,
  INDEX `idx_compra_fornecedor` (`fk_idFornecedor` ASC) VISIBLE,
  INDEX `fk_estado_compra` (`fk_idStatus` ASC) VISIBLE,
  CONSTRAINT `compra_materia_prima_ibfk_1`
    FOREIGN KEY (`fk_idMateriaPrima`)
    REFERENCES `pj_hermes`.`materia_prima` (`idMateriaPrima`),
  CONSTRAINT `compra_materia_prima_ibfk_2`
    FOREIGN KEY (`fk_idFornecedor`)
    REFERENCES `pj_hermes`.`fornecedor` (`idFornecedor`),
  CONSTRAINT `fk_estado_compra`
    FOREIGN KEY (`fk_idStatus`)
    REFERENCES `pj_hermes`.`status_id` (`idStatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 2001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`estoque_materia_prima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`estoque_materia_prima` (
  `idEstoqueMateriaPrima` INT NOT NULL AUTO_INCREMENT,
  `quantidadeEstoque` INT NOT NULL,
  `fk_idTransacaoCompra` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idEstoqueMateriaPrima`),
  INDEX `idx_estoque_transacaocompra` (`fk_idTransacaoCompra` ASC) VISIBLE,
  CONSTRAINT `estoque_materia_prima_ibfk_1`
    FOREIGN KEY (`fk_idTransacaoCompra`)
    REFERENCES `pj_hermes`.`compra_materia_prima` (`idTransacaoCompra`))
ENGINE = InnoDB
AUTO_INCREMENT = 3001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `idx_produto_preco_nome` (`preco` ASC, `nomeProduto` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`estoque_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`estoque_produto` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `quantidadeEstoque` INT NOT NULL,
  `fk_idProduto` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idEstoque`),
  INDEX `idx_estoque_produto` (`fk_idProduto` ASC) VISIBLE,
  CONSTRAINT `estoque_produto_ibfk_1`
    FOREIGN KEY (`fk_idProduto`)
    REFERENCES `pj_hermes`.`produto` (`idProduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 3001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`ordem_producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`ordem_producao` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NULL DEFAULT NULL,
  `dataFinal` DATE NULL DEFAULT NULL,
  `quantidadeProduzida` INT NULL DEFAULT NULL,
  `custo` DECIMAL(10,2) NULL DEFAULT NULL,
  `dataValidade` DATE NULL DEFAULT NULL,
  `fk_idProduto` INT NULL DEFAULT NULL,
  `fk_idStatus` INT NULL DEFAULT NULL,
  `data_criacao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idLote`),
  INDEX `fk_idProduto` (`fk_idProduto` ASC) VISIBLE,
  INDEX `idx_ordemproducao_quantidade_custo` (`quantidadeProduzida` ASC, `custo` ASC) VISIBLE,
  INDEX `idx_ordemproducao_dataInicio` (`dataInicio` ASC) VISIBLE,
  INDEX `idx_ordemproducao_dataFinal` (`dataFinal` ASC) VISIBLE,
  INDEX `fk_estado_ordem` (`fk_idStatus` ASC) VISIBLE,
  CONSTRAINT `fk_estado_ordem`
    FOREIGN KEY (`fk_idStatus`)
    REFERENCES `pj_hermes`.`status_id` (`idStatus`),
  CONSTRAINT `ordem_producao_ibfk_1`
    FOREIGN KEY (`fk_idProduto`)
    REFERENCES `pj_hermes`.`produto` (`idProduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 10001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pj_hermes`.`vinculo_produto_materiaprima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pj_hermes`.`vinculo_produto_materiaprima` (
  `idProdutoMateriaPrima` INT NOT NULL AUTO_INCREMENT,
  `fk_idProduto` INT NULL DEFAULT NULL,
  `fk_idMateriaPrima` INT NULL DEFAULT NULL,
  `dataLancada` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idProdutoMateriaPrima`),
  INDEX `idx_vinculo_dataLancada` (`dataLancada` ASC) VISIBLE,
  INDEX `idx_vinculo_produto` (`fk_idProduto` ASC) VISIBLE,
  INDEX `idx_vinculo_materiaprima` (`fk_idMateriaPrima` ASC) VISIBLE,
  CONSTRAINT `vinculo_produto_materiaprima_ibfk_1`
    FOREIGN KEY (`fk_idProduto`)
    REFERENCES `pj_hermes`.`produto` (`idProduto`),
  CONSTRAINT `vinculo_produto_materiaprima_ibfk_2`
    FOREIGN KEY (`fk_idMateriaPrima`)
    REFERENCES `pj_hermes`.`materia_prima` (`idMateriaPrima`))
ENGINE = InnoDB
AUTO_INCREMENT = 3001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
